name: Make Opening Book

on:
  workflow_dispatch:

jobs:
  make-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Polyglot
      run: |
        sudo apt-get update
        sudo apt-get install -y polyglot

    - name: Build win.bin from win.pgn
      run: |
        polyglot make-book -pgn win.pgn -bin win.bin -min-game 1

    - name: Upload win.bin
      uses: actions/upload-artifact@v4
      with:
        name: win-book
        path: win.bin
